blank_issues_enabled: false
contact_links:
  - name: Comunidad de Facebook
    url: https://www.facebook.com/share/g/2f2i6JGcNJZun2rV/
    about: Si tienes cualquier comentario no dudes en interactuar por aca
