name: Sugerencia de Funcionalidad
description: Sugiere las funcionalidades
title: "[Enhancement]: "
labels: ["enhancement"]
projects: ["Brain-DuCO/15"]
body:
  - type: markdown
    attributes:
      value: |
        En el Universo Arithmental nos encanta escuchar a nuestros usuarios. 
        Si tienes alguna sugerencia de algo que te gustaría ver o crees que algo se podría hacer de una mejor manera, ¡nuestro equipo estará dispuesto a escucharte!
  - type: input
    id: contact
    attributes:
      label: Detalles de Contacto
      description: ¿Cómo podemos contactarnos contigo si necesitamos más información?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: ¡Cuéntanos tu idea!
      description: ¡Danos todos los detalles de la idea!
      placeholder: En la pantalla de Feedback creo que podrían agregar...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        En los próximos días nuestro equipo dará una respuesta a tu propuesta. ¡Muchísimas gracias de antemano!
