name: Reporta un Error
description: ¡Ayúdanos a encontrar problemas!
title: "[Bug]: "
labels: ["bug"]
projects: ["Brain-DuCO/15"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tomarte el tiempo de reportar un error!
  - type: input
    id: contact
    attributes:
      label: Detalles de Contacto
      description: ¿Cómo podemos contactarnos contigo si necesitamos más información?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Qué sucedió?
      description: Cuéntanos los detalles de tu error.
      placeholder: ¡Dinos qué ves!
      value: "¡Sucedió este error!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: ¿En qué navegador sucedió esta experiencia?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tomarte el tiempo de reportar este problema! De antemano, perdón por esta experiencia. El equipo del Universo Arithmental trabajará rápido para que no vuelva a pasarle a nadie más.
